# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# Line length - disabled for flexibility
MD013: false

# Allow multiple headings with same content
MD024:
  siblings_only: true

# Allow inline HTML (needed for terraform-docs)
MD033: false

# Allow bare URLs
MD034: false

# First line should be a top-level heading
MD041: false

# Code block style
MD046:
  style: fenced

# Proper names capitalization
MD044:
  names:
    - Terraform
    - GitHub
    - AWS
    - Quorum
  code_blocks: false
  html_elements: false
